### ISSUE TITLE
Clean build folder

### ISSUE THREAD

**Issue by mcarans** [dave-shawley/setupext-janitor#17]
Thanks for what looks like a useful tool adding functionality missing in setuptools. As far as I can tell from the docs, this doesn't clean the build folder. Could this feature be added?

**Comment by mcarans** [comment]
I see the standard clean does that.

**Comment by bhrutledge** [comment]
@dave-shawley This might still be an issue. Using just `python setup.py clean` doesn't seem to remove the `build` directory, though `python setup.py clean --all` does. However, with this extension, `--all` also removes venvs and `__pycache__`, which I don't necessarily want.

I guess it'd be nice to do have something like:

```
python setup.py clean --build --dist --eggs
```

Or maybe an `--all-build` flag that does all of those three.

**Comment by mcarans** [comment]
Reopening for @bhrutledge comment above

**Comment by dave-shawley** [comment]
@mcarans you are on top of GH today 😮
