### ISSUE TITLE
Breaks matplotlib's setup.py

### ISSUE THREAD

**Issue by ionelmc** [dave-shawley/setupext-janitor#7]
It appears that matplotlib has a setupext.py file, for whatever reason, and that breaks if setupext-janitor is installed.

Is the setupext nspackage thing really necessary?

**Comment by ionelmc** [comment]
Btw, error looks like this (pip install ....):

```
  Using cached matplotlib-1.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-fRdmgH/matplotlib/setup.py", line 52, in <module>
        from setupext import print_line, print_raw, print_message, print_status
    ImportError: cannot import name print_line

    ----------------------------------------
```

**Comment by dave-shawley** [comment]
Not sure how I missed this for so long.  I apologize for that.  I went on a binge of writing setuptools libraries and was going to use a namespace package to contain them but it really is unnecessary.  The PR (#8) looks good.  Could you update the readme as well?
